# Cilium values for Cluster 2 (k3s-local)
operator:
  replicas: 1
cluster:
  name: k3s-local # Change it with the name you have given to your Cluster 2, matching the name in the cluster-info
  id: 2
kubeProxyReplacement: true
clustermesh:
  useAPIServer: true
  apiserver:
    service:
      type: LoadBalancer
k8sServiceHost: "192.168.100.101" # Change it with the IP of your Cluster 2 node
k8sServicePort: 6443
l2announcements:
  enabled: true
devices: eth+
externalIPs:
  enabled: true
externalTrafficPolicy: Cluster
internalTrafficPolicy: Cluster
ipam:
  mode: cluster-pool
  operator:
    clusterPoolIPv4PodCIDRList:
      - "10.245.0.0/16"
ingressController:
  enabled: true
  loadbalancerMode: dedicated
hubble:
  relay:
    enabled: true
  ui:
    enabled: true
  tls:
    enabled: true