# Cilium values for Cluster 3 (k3s-azure)
operator:
  replicas: 1
cluster:
  name: k3s-azure # Change it with the name you have given to your Cluster 3, matching the name in the cluster-info
  id: 3
kubeProxyReplacement: true
# clustermesh:
#   useAPIServer: true
#   apiserver:
#     service:
#       type: LoadBalancer
k8sServiceHost: "192.168.200.4" # Change it with the IP of your Cluster 3 node
k8sServicePort: 6443
l2announcements:
  enabled: true
devices: eth+
externalIPs:
  enabled: true
externalTrafficPolicy: Cluster
internalTrafficPolicy: Cluster
ipam:
  mode: cluster-pool
  operator:
    clusterPoolIPv4PodCIDRList:
      - "10.246.0.0/16"
ingressController:
  enabled: true
  loadbalancerMode: dedicated
hubble:
  relay:
    enabled: true
  ui:
    enabled: true
  tls:
    enabled: true