# Cilium values for Cluster 1 (k8s-main)
operator:
  replicas: 1
cluster:
  name: kubernetes # Change it with the name you have given to your Cluster 1, matching the name in the cluster-info
  id: 1
kubeProxyReplacement: true
clustermesh:
  useAPIServer: true
  apiserver:
    service:
      type: LoadBalancer
k8sServiceHost: "192.168.100.100" # Change it with the IP of your Cluster 1 node
k8sServicePort: 6443
l2announcements:
  enabled: true
devices: eth+
externalIPs:
  enabled: true
externalTrafficPolicy: Cluster
internalTrafficPolicy: Cluster
ipam:
  mode: cluster-pool
  operator:
    clusterPoolIPv4PodCIDRList:
      - "10.244.0.0/16"
ingressController:
  enabled: true
  loadbalancerMode: dedicated
hubble:
  relay:
    enabled: true
  ui:
    enabled: true
  tls:
    enabled: true