apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "general-pool"
spec:
  blocks:
  - start: "192.168.100.170"
    stop: "192.168.100.219"

---

apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: policy1
spec:
  interfaces:
  - ^eth[0-9]+
  externalIPs: true
  loadBalancerIPs: true